Add unit tests for standard output truth csv
reichlab/covidHubUtils pull request #118
Opened 2021-01-11 14:02 UTC by Khoale1096

2021-01-13 19:00 UTC, elray1 requested changes
I got a couple of failed tests here, and had a question about handling of expected outputs for DC.  Thanks!

2021-01-20 15:12 UTC, Khoale1096 commented on tests/testthat/test-get_truth.R
> +test_that("preprocess_jhu files has expected combinations of location, week", {
Sorry it's my bad. I have a commit that already resolved this but didn't push it through

2021-01-20 15:12 UTC, Khoale1096 commented on tests/testthat/test-get_truth.R
> +  expected_cumulative_deaths <- expected[,c("date", "location", "cum")] %>%
Sorry it's my bad. I have a commit that already resolved this but didn't push it through

2021-02-01 17:32 UTC, Khoale1096 commented
@elray1 I have compared the outputs of these new methods with the output of the python scripts. There is only one discrepancy, which is that the incident cases/deaths output of the python scripts do not have any negative values due to thresholding at this [code](https://github.com/reichlab/covid19-forecast-hub/blob/master/data-truth/truth_utils/_utils.py#L155). However, we decided [here](https://reichlab.slack.com/archives/C011SKXLBA8/p1607106472289400?thread_ts=1606752765.242800&cid=C011SKXLBA8) that we would like to not truncate these negative values. So I removed the thresholding code on the python side and the output of the two codes match. Is there any other check I should do before merging this in?

2021-02-03 16:04 UTC, merged